language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: eT0Lu+JLN9xFhKXGSQZv3d1eMI6RZA3WpucCaUSBfwe4vR+IOs5yndDoR3GQzcJD9c0gtyyWwJoRC19z2iEtmZK65ovVbPkV6jrDSiZKW7PLF7j7TBb0W/C9o1syr05u1m9tsSrM58ULyAPsnOBJDOJGYHKCfB22zM/mwajKvSexLWYIlv780f07GZQnoBx+x3g3Pr+g1+N+UfwhqlV7DNfTwjWcs9owdzVojahagnONvwS1efYrgeASW/UWZYPTMLLUDBUyWqRDVs5+TVmZ1fYbKNdE0f3QgdjZpryp0LhttP6k0sPDcgUUEBcT09IoMTbETwmDplI5+5GIRifDGGPZHFM59mV1yUcLuZqJDFGPWir1VzAsAX7j7NRoljEi0mjiEnlvRjcyZL5vb+gWp0GjcWTdFuanBJQF4xXLT6Nb90qIRee5Yh/cs6B3Y0taZuIaIiRnbl85MU2fRlALUu0N05vZOEKVBuC+E4i/iDHvPeuBcQbOVSvJuRJDpb3SOXU6ktu/NcyOiHEwpVcy398Ei/HtIEMIr82bMFZ9JAnv4TS9E8g+s76GwF1upTyMxEr2PSx4pv0W/X0gg7N3GNaMyid4vhsi7rJAgNib4c+VdguUEu5qkXj94fT0/PhmS0ztBSR/tQiBMk3sE5xXctZT07Od9gRypMVd2gT7nMg=
  app: limitless-bayou-94722
  on:
    repo: midimurphdesigns/restaurants-tests
    branch: feature/with-tests
