language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: XWATBJbrRu1oGpfNZBWRXFUBZQFhOxPk418ESsctaIyqmrfsdnC61P9c/+S2TJZCZ7JLZV3oz43qMy3R2/G4Opi45qMRGIQoFkMg2qvlTnXNT4yTxYLhr4OLb3OZysfLubqJUgcBABZFS7u13S7NDGXZDHKjgTxEEdI6Mc0tL5x3Ztr7GKwdPbBAaQ5pctS8W4oVUBa7GUEzr1b9a3N/crcrwnRI5zK4yw4OBIbVtsXAQS3+X39EZ1TjYj8n6OyAgcw+2bw14fa+PgeuppMFMp3EfjO49OVH12zA8IR6CgRjYO3pkiKAZAQcQAeahOZfr+DKaS85foYnnhgONgAEi6e2KtxdhrfbFgXbYBQlZUbClEdT9o6p0M99eQ+ajEy7TAccAhiY9puNBdtY5Cl8Ci8urAUsKYuLPNq5oo8J6/DS3HeOnMs+pV5/H+QwMm1W1oisnxBAok4I72CyoBZ8KImtIeEFjYmQ7muHvvTKnEN4OVsAmSXzKwOuppWpp8W6glCxawQWsnGYU4PSIW91VHoDOc+HpwzKCD5W4eXYuowhTiIxghwHlVzAZgP/iDnQWztDIegsLC4HGs0EoP/lDAgH3/a9kpEzSsl/J/xa6Lj/WgZxNYHCLbzVc8yFrvnR9Sw53OvafLdcNSjmRAKjfgQgEykaKaxBYRjYLgblL0E=
  app: restaurants-tests
  on:
    repo: midimurphdesigns/restaurants-tests
    branch: feature/with-tests
